name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
      name: Install dependencies

    - name: Install PM2
      run: npm install -g pm2

    - name: Set up environment variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV

    - name: Print working directory and list files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in the current directory:"
        ls -la

    - name: Change Directory and Start Application with PM2
      run: |
        # Change this to the correct directory where your `index.js` is located
       
        pm2 start index.js --name index
        pm2 save
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    - name: Verify PM2 processes
      run: |
       
        pm2 list

    - name: Output PM2 logs
      run: |
        
        pm2 logs
